### ISSUE TITLE
Sky & Fog color issues

### ISSUE THREAD

**Issue by ghost** [kvverti/colormatic#10]
The sky and fog colors are not displaying my custom ones and they flicker. Here is a short clip of it happening:
https://imgur.com/a/f33ODFd

I am not using any other mods, except for the Fabric API and ModMenu. It only happens when I have a resource pack on. This is the one I was testing this issue with, which does work with OptiFine https://drive.google.com/drive/folders/1joRQFnFk0TFy16D9NA0MzJTZCOQq1Xhi?usp=sharing

**Comment by kvverti** [comment]
Please provide the following:
- Minecraft Version
- Resource pack list
- Video settings
- Colormatic mod options

This _may_ be a result of biome temperature blending + your video settings + the resource pack.

**Comment by kvverti** [comment]
Closed due to inactivity
