### ISSUE TITLE
Create Fabric Incompatibility

### ISSUE THREAD

**Issue by ardissaps** [kvverti/colormatic#100]
https://github.com/Fabricators-of-Create/Create/issues/387

**Comment by kvverti** [comment]
Fixed in 3.1.2

**Comment by ardissaps** [comment]
> Fixed in 3.1.2

will it available for 1.18.2?

**Comment by gnomed-by-steve** [comment]
> will it available for 1.18.2?
Hoping so, can't be that hard to backport. This along with the quilt toolchain compatibility would be a godsend for 1.18.2 users.

**Comment by ardissaps** [comment]
> > will it available for 1.18.2?
> 
> Hoping so, can't be that hard to backport. This along with the quilt toolchain compatibility would be a godsend for 1.18.2 users.
> 
> Update: you can actually manually build commit [3306373](https://github.com/kvverti/colormatic/commit/3306373692da02338fd6efbdc42cf605a80ba602) and it'll fix this particular issue. If it's never properly released, you can at least do this.

Does it as simple as it just change version number? If yes then need to extract and edit with notepad or so.

**Comment by ardissaps** [comment]
@gnomed-by-steve hello sir how to get that build, I don't understand, help would be appreciated

**Comment by sisby-folk** [comment]
[checks license]

@ardissaps christmas present
[colormatic-3.1.2-snapshot+mc.1.18.2.jar.zip](https://github.com/kvverti/colormatic/files/9185740/colormatic-3.1.2-snapshot%2Bmc.1.18.2.jar.zip)

**Comment by ardissaps** [comment]
> [checks license]
> 
> @ardissaps christmas present [colormatic-3.1.2-snapshot+mc.1.18.2.jar.zip](https://github.com/kvverti/colormatic/files/9185740/colormatic-3.1.2-snapshot%2Bmc.1.18.2.jar.zip)

oh thanks! :p

**Comment by gnomed-by-steve** [comment]
> [checks license]
> 
> @ardissaps christmas present [colormatic-3.1.2-snapshot+mc.1.18.2.jar.zip](https://github.com/kvverti/colormatic/files/9185740/colormatic-3.1.2-snapshot%2Bmc.1.18.2.jar.zip)

oh, the license allows that? yippee!!!
