### ISSUE TITLE
Lava colormaps don't function on 1.19

### ISSUE THREAD

**Issue by owosoup** [kvverti/colormatic#101]
using the 'Pew's vanilla' resource pack, the lava textures reset to the default tint, making the nether biomes all have the same lava.
on 1.18.2, it works properly, but not on 1.19.  
It shouldn't be too bad, replacing the malfunctioning part with the former version, or at least copying it, should be easy (I'm not a mod dev but I hope it is as simple as that :')

**Comment by kvverti** [comment]
Probably the same issue as #105
