### ISSUE TITLE
Incorrect emulation of colormaps (might be "grid" format specific?)

### ISSUE THREAD

**Issue by coornio** [kvverti/colormatic#105]
Either incorrect, or perhaps non-existent? Either way, hello! I am back once more and although I noticed late, the water fog is (and potentially others) are not having their colormap applied. This is all tested in 1.18.2 (since OF hasn't released for 1.19 yet)

This is how it looks in OptiFine, underwater in a Deep Cold Ocean specifically: 
![image](https://user-images.githubusercontent.com/11655762/175323283-94fd3f63-6b68-480a-80f8-9c3bd573ab7f.png)

This is in vanilla, no mods:
![image](https://user-images.githubusercontent.com/11655762/175324101-eeec64d7-caf8-41ed-844f-28ba8840f128.png)

And this is in fabric with Colormatic installed. Practically no difference:
![image](https://user-images.githubusercontent.com/11655762/175324497-93e52afb-2597-49b4-bec6-a60a3f9f1acd.png)

The files controlling this are specifically under `/assets/minecraft/optifine/colormap`, once again tested through the John Smith Legacy pack. Here's the `underwater.png` texture as an example:
![underwater](https://user-images.githubusercontent.com/11655762/175325018-39cd22fe-2268-4e6b-bb72-674bad38ced0.png)

How the folder's contents look. The `blocks` subfolder has colormaps for leaves. I don't know if those are also improper, I'd need to mess the textures up by painting all over them and go check for differences. 
![image](https://user-images.githubusercontent.com/11655762/175324978-48ae879e-acd9-43a5-8496-f69411e3c45b.png)

The relevant code from the properties file:
```# Format of colormap------------------------------------------------------------
format=grid

# (Optional) Blocks (with optional metadata) to apply the colormap to-----------

# (format=fixed or vanilla only) Color map image--------------------------------
source=underwater.png

# (Optional) Fixed RGB color----------------------------------------------------
#color=ffffff

# (format=grid only) y variance value-------------------------------------------
yVariance=5

# (format=grid only) y offset value---------------------------------------------
yOffset=-64
```
Lastly, the documentation for colormaps for optifine, in case it helps to have a shortcut to it:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/colormap.properties

According to the doc the map is meant to be 256x256 maximum, with Y being the build height. That probably changed back in the day when that became -64 to 320, but the use of an offset more or less corrects it. I can only assume that either the grid format isn't emulated, or perhaps Colormatic is failing to apply colors properly? 

I hope this information is helpful in debugging this and getting one step closer to feature parity <3

**Comment by kvverti** [comment]
This is because John Smith Legacy is including a `source` property that doesn't point to an image. The value should be `source=./underwater.png`. I'm not sure why Optifine is accepting this (do they not accept standard resource locations?). In any case, they don't need to specify this property anyway, as by default both mods use the name of the properties file as an image source.

**Comment by coornio** [comment]
Your comment confuses me due to the fact that the source did point to a picture actually, but given that you crossed it out and re-opened the issue, I'm guessing you found something wrong to fix in the coming release? :D
