### ISSUE TITLE
Crash with Advancement Frames + Biome Makeover

### ISSUE THREAD

**Issue by inflorescence91838** [kvverti/colormatic#107]
This is an unusual crash, as it requires at least these two mods to be present in order to crash. If any of the three mods are taken out, the crash doesn't happen. If only two (of any combination) are present, the game crashes.

Mod list
- Architectury API
- Fabric API
- Advancement Frames
- Biome Makeover
- Colormatic

[latest.log](https://github.com/kvverti/colormatic/files/9108163/latest.log)

**Comment by kvverti** [comment]
Please post your entire log file, including the crash.

**Comment by inflorescence91838** [comment]
[latest.log](https://github.com/kvverti/colormatic/files/9109000/latest.log)
[crash-2022-07-13_22.23.19-client.txt](https://github.com/kvverti/colormatic/files/9109002/crash-2022-07-13_22.23.19-client.txt)

The post already provided latest.log, but I'll upload it again alongside the crash log.

**Comment by kvverti** [comment]
Not a colormatic issue. Architectury is registering its objects too late for Fabric
