### ISSUE TITLE
Infinite loading when I use colormatic in my modpack (1.19)

### ISSUE THREAD

**Issue by SpiritOTHawk** [kvverti/colormatic#108]
[Log file](https://pastebin.com/x9vPh0Rn)
Yes, there are still some conflicts, but when you remove the colormatic, the game starts. It's more like an incompatibility with some of the mods.

**Comment by azridere** [comment]
Same issue when loading Itembound with CITResewn. Removing colormatic makes my game run perfectly fine.

**Comment by kvverti** [comment]
One of your resource packs contains an invalid resource location (one with a space). Optifine accepts these invalid resource locations but vanilla (and Fabric mods) do not. CIT Resewn has a Config setting to allow  invalid paths.
