### ISSUE TITLE
Create Incompatable mod set 

### ISSUE THREAD

**Issue by PanginoongJimmyG** [kvverti/colormatic#109]
Error Logs:
Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
<html>Remove mod 'Colormatic' (colormatic) 3.1.1+mc.1.18.2 
Unmet dependency listing:
<html>Mod 'Create' (create) 0.5.0c-708 is incompatible with version 3.1.1 or earlier of mod 'Colormatic' (colormatic), but a<br>matching version is present: 3.1.1+mc.1.18.2!</html>

Im using the  3.1.1+mc.1.18.2 that supposed to be the fix tried to reinstall the mods but the issue still persist.

**Comment by sisby-folk** [comment]
https://github.com/Fabricators-of-Create/Create/issues/387#issuecomment-1194851627

**Comment by sisby-folk** [comment]
If it's possible for y'all to release that ^ version to modrinth though, that would be appreciated.

**Comment by kvverti** [comment]
Done
