### ISSUE TITLE
Colormatic incorrectly recommends an old version of ModMenu

### ISSUE THREAD

**Issue by Legatum1** [kvverti/colormatic#110]
Logs:
[16:33:29] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.9
[16:33:35] [main/WARN]: Warnings were found!
 - Mod 'Colormatic' (colormatic) 3.1.2+mc.1.19 recommends any version of quilt_loader, which is missing!
	 - You should install any version of quilt_loader for the optimal experience.
 - Mod 'Colormatic' (colormatic) 3.1.2+mc.1.19 recommends any version between 3.0.0 (inclusive) and 4- (exclusive) of mod 'Mod Menu' (modmenu), but only the wrong version is present: 4.0.4!
	 - You should install any version between 3.0.0 (inclusive) and 4- (exclusive) of mod 'Mod Menu' (modmenu) for the optimal experience.

**Comment by kvverti** [comment]
This is just a warning and does not affect gameplay.

**Comment by lowa9** [comment]
I met this warning too,so I chose a lower version of modmenu and just apply both of the high version(mine here is 4.2.0-beta.2) and the lower version(3.2.5),it just work well
