### ISSUE TITLE
[Fabric] Crash with Supplementaries and Advancement Frames

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [kvverti/colormatic#111]
**MC** 1.19.2
**FAPI** 0.60.0
**[Moonlight Lib](https://www.curseforge.com/minecraft/mc-mods/selene)** 2.0.17
**[Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)** 2.0.14
**[Advancement Frames](https://www.curseforge.com/minecraft/mc-mods/advancement-frames)** 1.1.2
**Colormatic** 3.1.2

To reproduce simply install all the mods and launch the game.

A similar issue was reported in https://github.com/kvverti/colormatic/issues/107. However, when I reported this issue to Supplementaries, the developer told me that on Fabric there's no set place to register objects and Supplementaries intentionally registers itself later in order to create new blocks based of off already existing ones: https://github.com/MehVahdJukaar/Supplementaries/issues/330#issuecomment-1221416978.

I play primarily on Quilt and the issue doesn't happen there, but would it still be possible to do something about it on Fabric?

Logs: https://gist.github.com/Footage2-Amply-Pounce/8a9470e5592cb03acd00972e7ec7c415

**Comment by kvverti** [comment]
Not an issue with Colormatic
