### ISSUE TITLE
Crash with ad astra fluid

### ISSUE THREAD

**Issue by HmmmHmmmm** [kvverti/colormatic#114]
I've reported this on ad astra's github page , and when I contacted the owner of the mod he told that the error isnt caused by his mod .
I thought it might be sodium but when I tried to run them together to verify , they worked perfectly fine . I suspected it was colormatic since it also messes around with fluids . When I tried to run the mod along with sodium and ad astra! the bug came back 
Here is a link to the original issue , it contains alot useful information 
https://github.com/AlexNijjar/Ad-Astra-Fabric/issues/13

**Comment by HmmmHmmmm** [comment]
After more testing , I found out that when I use sodium+colormatic+ad astra! a visual bug appear for already placed fluids (the one noted in here --> https://github.com/AlexNijjar/Ad-Astra-Fabric/issues/13)
But when I play with colormatic alone, instead of just having a visual bug, it always immediatly crash whenever I look at the fluid .
Here is the crash report 
[crash-2022-09-13_12.43.36-client.txt](https://github.com/kvverti/colormatic/files/9556814/crash-2022-09-13_12.43.36-client.txt)

Mods used :
-colormatic
-fabric api
-ad astra!
-cloth config (required by ad astra!)

**Comment by kvverti** [comment]
This bug is fixed in the 1.19 version of Colormatic. A 1.18 compatibility release should be available soon.
