### ISSUE TITLE
Is mixin.features.fast_biome_colors completely using fast_biome_colors?

### ISSUE THREAD

**Issue by jacklollz2** [kvverti/colormatic#116]
Is mixin.features.fast_biome_colors completely using fast_biome_colors?
Fast biome colors improves the performance, and I just want to make sure fbc is fully implemented.

Force-disabling mixin 'features.fast_biome_colors.MixinBackgroundRenderer' as rule 'mixin.features.fast_biome_colors' (added by mods [colormatic]) disables it and children
Force-disabling mixin 'features.fast_biome_colors.MixinClientWorld' as rule 'mixin.features.fast_biome_colors' (added by mods [colormatic]) disables it and children

**Comment by kvverti** [comment]
Colormatic currently requires vanilla colormap handling to be present so it can inject into it. Sodium also does this which is why we disable it in Colormatic. In the future this restriction may no longer be necessary but I wouldn't hold your breath.
