### ISSUE TITLE
3-way incompatibility with TerraBlender and KubeJS causing a crash

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [kvverti/colormatic#117]
**MC** 1.19.2
**FAPI** 0.62.0
**Colormatic** 3.1.2
**[KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs)** 1902.6.0-build.79
**[TerraBlender](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)** 2.0.1.128

The game crashes on startup when all 3 mods are present. Removing either one lets the game start.

Logs: https://gist.github.com/Footage2-Amply-Pounce/d60f5fc9d9bdd1f101c0041926f0ce9d

Reported to KubeJS and TerraBlender as well: https://github.com/KubeJS-Mods/KubeJS/issues/500; https://github.com/Glitchfiend/TerraBlender/issues/93.

**Comment by kvverti** [comment]
This looks like an issue with terrablender registering its biomes too late (again)

**Comment by Footage2-Amply-Pounce** [comment]
Sorry! Just making sure.
