### ISSUE TITLE
Crash on startup with KubeJS and Tech Reborn and/or Modern Industrialization

### ISSUE THREAD

**Issue by Waoweens** [kvverti/colormatic#119]
If Colormatic, KubeJS, and either Tech Reborn or Modern Industrialization (they both crash the same way) is installed, the game will crash on startup. (It will also crash if both is installed)

Log: https://gist.github.com/Waoweens/4666d5312e8af1b06ef14951fa6e70c1

| Mod | Version |
| - | - |
| Minecraft | 1.19.2 |
| Fabric Loader | 0.14.9 |
| Fabric API | 0.64.0+1.19.2 |
| Colormatic | 3.1.2+mc.1.19 |
| Architectury | 6.3.49 |
| Rhino | 1902.2.1-build.242 |
| KubeJS | 1902.6.0-build.101 |
| Tech Reborn | 5.3.4 |
| Cloth Config v8 |  8.2.88 |
| Roughly Enough Items | 9.1.562 |
| Modern Industrialization | 1.3.2 |

<details>
<summary>Extra</summary>

PS: I had a hard time trying to Google the error, so here's some snippets:
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'modern_industrialization'!`
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tech_reborn'!`

</details>

**Comment by kvverti** [comment]
Please report this to modern industrialization; they are registering things after the registries are frozen. *Colormatic does not modify the behavior of registries*.
