### ISSUE TITLE
crashing on 1.19.3

### ISSUE THREAD

**Issue by mrjasonn** [kvverti/colormatic#123]
need to update to 1.19.3, its crashing on 1.19.3

**Comment by nightngaleD** [comment]
Having the same issue, checking the logs and it says that Quilt is missing and that I'm using the wrong version of Mod Menu (5.0.2), I was under the impression this worked on fabric

**Comment by mrjasonn** [comment]
I don’t have a mod menu issue, it’s just straight up not letting me launch
on 1.19.3. Plus I have not included mod menu in my mods folder.

**Comment by rayzchen** [comment]
Seems to work on 1.19 but not 1.19.3 (haven't tested any other versions)

**Comment by Dinhero21** [comment]
When I load it up alone in 1.19.3 it just crashes with error code 1. Here are my [logs](https://github.com/kvverti/colormatic/files/10329028/latest.log).

**Comment by giorov** [comment]
Same, thanks.

**Comment by fedetrifo06** [comment]
#126
