### ISSUE TITLE
Cross mod interaction crash

### ISSUE THREAD

**Issue by zabi94** [kvverti/colormatic#13]
If I understand correctly the following mixin injection assumes no mod will call the getColor method before the property objects are initialized, and it may be the cause of this crash that was reported to me: https://github.com/zabi94/ExtraAlchemy/issues/81

https://github.com/kvverti/colormatic/blob/7f770e022904f8edb714c6afc908881ce88c6ba5/src/main/java/io/github/kvverti/colormatic/mixin/potion/StatusEffectMixin.java#L35-L42

All the details are included by the user in that report

**Comment by zabi94** [comment]
This is the stack trace: https://pastebin.com/raw/WMqvtL5m
This is where I call the method, nothing is null on my side: https://github.com/zabi94/ExtraAlchemy/blob/5e64eecc6c5a0f361a5869027708cfc8e3e406f4/src/main/java/zabi/minecraft/extraalchemy/statuseffect/ModEffectRegistry.java#L69

**Comment by kvverti** [comment]
`bad000` - guess it was bad lol. Looks like you fixed it on your end, but I can look into gating the access behind a check or making sure the properties are initialized. Note that if you cache the colors before resource reload, they may be incorrect regardless.

**Comment by zabi94** [comment]
😂 Jokes aside, I'm kinda curious about where the bad000 name comes from. At first I thought it might be the obfuscated class name for StatusEffect, but it's not

**Comment by kvverti** [comment]
`bad000` is the name mixin prepends to the callback for name mangling purposes.

**Comment by zabi94** [comment]
Curious name choice then
