### ISSUE TITLE
Update myself ?

### ISSUE THREAD

**Issue by Darukshock** [kvverti/colormatic#135]
I would really like a version of this mod updated to 1.20. Is there a simple way to make it work without crashing the game, or do I wait for you to update ? Great mod !

**Comment by Shulzky** [comment]
> I would really like a version of this mod updated to 1.20. Is there a simple way to make it work without crashing the game, or do I wait for you to update ? Great mod !

If it's possible please do

**Comment by Spittys** [comment]
If you do plan on updating this please send me the mod, thank you

**Comment by kvverti** [comment]
Consolidating 1.20 update in #136
