### ISSUE TITLE
Update to 1.20 & 1.20.1

### ISSUE THREAD

**Issue by gitdrug** [kvverti/colormatic#136]
Update to 1.20 & 1.20.1

**Comment by Spittys** [comment]
bump

**Comment by GLeviathan** [comment]
Yeah we need this badly. It's been broken since 1.19.4 on a lot of support for texture packs.

**Comment by shadowtigercool** [comment]
bump

**Comment by NattoRiisa** [comment]
judging by their activity they're probably busy

**Comment by GLeviathan** [comment]
> judging by their activity they're probably busy

Yeah or they forgot about it xD

**Comment by GrassyTrams** [comment]
itd be really really good to have this for 1.20, this mod is super important.

**Comment by Arrocha08** [comment]
im not alone lol

**Comment by GLeviathan** [comment]
Still nothing :(

**Comment by punctdan** [comment]
The latest change they made is from Feb 4 which just changes mod version from 3.1.2 to 3.1.3 snapshot. 🤷

**Comment by Poopooracoocoo** [comment]
There's no need to bump here. There is no stale bot in this repo. You're not sending notifications to any maintainers or contributors. You're just sending notifications to anyone that has subscribed/commented to this issue. People subscribed to this issue are hoping that a contributor will discuss how they can port this or to know when this will be closed and ported.

**Comment by tliron** [comment]
I don't want to bump! I just want to be nicer about this request. :) Thank you so much to all who work on this excellent mod. It has become so important for many of us who rely on custom colors in our resource packs. I just want you to know that your work is *very* widely appreciated, and that is why people are so eager (and not always very polite) about asking for timelines.

**Comment by xlifi** [comment]
There's someone in [this thread](https://discord.com/channels/507304429255393322/1126422887591596113) on FabricMC discord server making a [new mod](https://github.com/theomenden/TheOmenDen.Vanadium) to replace this one

**Comment by 4unduck** [comment]
damn still nothing

**Comment by xlifi** [comment]
> damn still nothing

![Screenshot_2023-08-14-13-45-15-72_ce48f3669154ad2f53ee7715a6cfbfc3.jpg](https://github.com/kvverti/colormatic/assets/70767436/4d07c1d7-7cd8-4ba4-a4ab-baa5ed3121ae)

**Comment by MithicSpirit** [comment]
> damn still nothing

Not nothing. Commit 0ebb7800f97c7b520a82cdfc301edc9dba2ee2f1 from last week shows that 1.20 support is clearly being worked on.

**Comment by 4unduck** [comment]
oh nice

**Comment by 4unduck** [comment]
im stupid sorry

**Comment by sasquott** [comment]
> > damn still nothing
> 
> ![Screenshot_2023-08-14-13-45-15-72_ce48f3669154ad2f53ee7715a6cfbfc3.jpg](https://user-images.githubusercontent.com/70767436/260353228-4d07c1d7-7cd8-4ba4-a4ab-baa5ed3121ae.jpg)

Hasn’t IMS (Iris dev) already helped isolate the biomes in a fork? Think it was the registry needing manually changed that was left to do

**Comment by zuliwa** [comment]
Any progress at all in the last three weeks?

**Comment by hoodman009** [comment]
bump

**Comment by 0v8v0** [comment]
someone in Reddit said "it seems the author has died"  is this true ?
i hope not :(

**Comment by Anoaxx** [comment]
dot

**Comment by Macintosh-Fan** [comment]
Still not out.

**Comment by IntMarco** [comment]
Use this:
https://modrinth.com/mod/polytone

It is maintained and has many more functions.
