### ISSUE TITLE
Error when reading color.properties

### ISSUE THREAD

**Issue by dexman545** [kvverti/colormatic#15]
This error is logged when reading color.properties from John SMith Legacy - JimStoneCraft Edition:
'Error parsing minecraft:optifine/color.properties: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 664 path $.text.sign'

color.properties: https://gist.github.com/dexman545/1c47efca56009aefa084db1c285fa3b5

**Comment by JimStoneCraft** [comment]
Comment out the line for the text.sign to remove the error, good as a temporary fix..

text.sign=404040

to

# text.sign=404040

**Comment by dexman545** [comment]
Alright, thanks!
