### ISSUE TITLE
Dimension IDs compared using reference equality

### ISSUE THREAD

**Issue by dehen** [kvverti/colormatic#16]
Not sure if you're going to support this, because maybe sky0.png is an older format than json? But you asked to report parity issues so here I am.

[Jolicraft](http://jolicraft.com/) is an older continually updated pack. There's something funky going on with sky color. Jolicraft has pretty dramatic color shifts in optifine, but in colormatic, there seems to be some different behavior going on, as if the mod color is being blended with a default color? Like I'm still seeing some subtle changes but not like in optifine.

So here's a savanna. Washed out sky in optifine, as intended:
![image](https://user-images.githubusercontent.com/10331141/90593474-3b5c9c80-e1a5-11ea-97ca-1f5cec54c019.png)
Here it is in colormatic. Only mods are fabricapi, colormatic, and the jolicraft pack:
![image](https://user-images.githubusercontent.com/10331141/90594106-d86c0500-e1a6-11ea-908e-6b3f6493ae9e.png)

I like the joli colors, but it wasn't a big deal. But then I went to the nether on some server and saw this very broken fog. It doesn't seem to change across nether biomes, and it's not white in optifine, I also testing removing colormatic and everything was fine:
![image](https://user-images.githubusercontent.com/10331141/90594247-30a30700-e1a7-11ea-9e7b-425881d93e8c.png)

What's weird is that colormatic is different in my local single player:
![image](https://user-images.githubusercontent.com/10331141/90594457-b32bc680-e1a7-11ea-8e46-cbceea1d77e6.png)

I don't even know what's going on.
At any rate:
Minecraft 1.16.2
colormatic-2.2.4+mc.1.16.2-rc1
fabric-api-0.18.0+build.397-1.16.jar
Pretty sure the server is vanilla 1.16.2

Anyways, good luck on the mod. Hope this helps some.

**Comment by danjacobsen1** [comment]
If you add a sky0.properties and fog0.properties file it should work. If it still does not work try to move the sky0 and fog0 files (.png and .properties) into the optifine/colormap/custom folder. I believe this because colormatic expects properties files for sky0 and fog0 while optifine does not.

**Comment by kvverti** [comment]
Just a reference equality issue; will push an update!

**Comment by kvverti** [comment]
Fixed in 2.2.6

**Comment by Jarfeh** [comment]
This issue has not been fixed. The fog still changes into the overworld-like color while in a server.

**SERVER**
![2020-12-30_16 24 23](https://user-images.githubusercontent.com/58902941/103387982-a014f580-4abb-11eb-9030-881aecc16395.png)

**SINGLE PLAYER**
![2020-12-30_16 24 33](https://user-images.githubusercontent.com/58902941/103387988-a2774f80-4abb-11eb-9d22-c9cff19c73a3.png)
