### ISSUE TITLE
Non-tinted blocks colormaps do not work

### ISSUE THREAD

**Issue by ghost** [kvverti/colormatic#17]
Version: both the latest colormatic versions for 1.16.1 and 1.16.2

Custom colormaps do not seem to work with blocks that do not have a hardcoded tint. For example leaves and grass block colormaps work fine, but dirt and sand do not work. I have noticed that the block breaking particles do change to the color supplied in the colormap, but the block itself does not. 

Here is an example pack that shows this issue: [colormatic-test](https://drive.google.com/file/d/1YWTT03RKR_56UbHHW0o9vKvMXfRhfI3B/view?usp=sharing). I have tried it in both the colormatic and optifine format.

Let me know if you are unable to reproduce it so I can post my settings.

**Comment by puzzlecube** [comment]
This also seems to effect 1.16.3 too. I have tested with Sodium, Canvas, and default renderers all with the same results. I have also tested on 1.16.2 with Canvas and default renderers and it does not work in that version either.
This seemed to be the case with both the colormatic-test pack you posted and with an all biomes test colormap. The mod does not log any warnings or errors when loading the JSON either.

**Comment by kvverti** [comment]
This is because Colormatic does not modify block models to be tintable. It is in the backlog to be added when I get a chance to understand the Fabric rendering API.

**Comment by yungando** [comment]
So, from the current mod description on Curseforge:

> - Custom biome colormaps for any block

This isn't the case at the moment, or am I miss-understanding?

**Comment by kvverti** [comment]
Marking this as "won't fix"; any fix would be dependent on a specific rendering API implementation.

**Comment by Luke18033** [comment]
Seems like this should be closed?
