### ISSUE TITLE
Custom lightmap gives unwanted tint to parts of the GUI

### ISSUE THREAD

**Issue by danjacobsen1** [kvverti/colormatic#18]
Vanilla uses the lightmap when rendering text, items and blocks in the GUI. For this it uses maximum block and sky light.
In vanilla this is always white but with custom lightmaps this is not always the case, causing parts of the UI to have a tint. This is for example noticeable in [pixel-reality-luminance](https://www.curseforge.com/minecraft/texture-packs/pixel-reality-luminance).

I think this is unwanted behaviour. Disabling the custom lightmap when rendering the GUI (like optifine does), or an option to do this would be nice.

Also, thank you for creating this mod. :)

**Comment by kvverti** [comment]
See #6
