### ISSUE TITLE
Optifine properties files fail to load when hex colours contain trailing spaces

### ISSUE THREAD

**Issue by zml2008** [kvverti/colormatic#19]
In the [Lithos](https://www.curseforge.com/minecraft/texture-packs/lithos-core-32x-1-6-1-11-complete) pack, some of the lines in `assets/minecraft/optifine/color.properties` have trailing spaces, which cause `parseInt()` in the `HexColorAdapter` to fail.

This causes a load failure for the color properties file, but the rest of the resource pack still comes in fine.

**Comment by kvverti** [comment]
Ah Optifine again with it's annoyingly permissive parsing rules.
