### ISSUE TITLE
Crash on load in 1.16.4

### ISSUE THREAD

**Issue by MechanosG** [kvverti/colormatic#23]
Testing to see if this would work with 1.16.4, I get this error -

> [19:10:22] [main/FATAL]: Mixin prepare failed preparing compat.IdentifierMixin in colormatic.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: colormatic.mixins.json:compat.IdentifierMixin target net.minecraft.class_2960 was loaded too early.
> org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: colormatic.mixins.json:compat.IdentifierMixin target net.minecraft.class_2960 was loaded too early.
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:938) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.10.6+build.214.jar:0.8.2+build.24+unknown-b24.git-unknown]
> 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
> 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
> 	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:272) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) ~[fabric-loader-0.10.6+build.214.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
> 	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171) ~[?:?]
> 	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[?:?]
> 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131) ~[?:?]
> 	at java.util.HashMap$Values.forEach(Unknown Source) [?:1.8.0_271]
> 	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131) [modlauncher-8.0.6.jar:?]
> 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56) [modlauncher-8.0.6.jar:?]
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76) [modlauncher-8.0.6.jar:?]
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
> 

RER also gave me a very similar error upon updating to 1.16.4.  1.16.3 works fine though.  Lemme know if you need any additional information.

MC 1.16.4
Fabric 0.6.1.51
Colormatic 2.2.7

**Comment by kvverti** [comment]
What is your full mod list?
