### ISSUE TITLE
Using Night Vision with Lightmaps of 16*32 (without night vision lighting) crashes the game in the nether and in the end

### ISSUE THREAD

**Issue by TrinalDust** [kvverti/colormatic#24]
Night Vision with Lightmaps of 16*32 (without night vision lighting) crashes the game in the nether and in the end but not in the overworld

MC version: 1.16.4
Fabric Loader: 0.10.8
Using a Resource Pack with colormatic setup (not Optifine setup)
Lightmaps work perfectly in the overworld with and without the night vision part
NOT using Optifabric but using Sodium
The Pack only changes Lightmaps and is the only resource pack
In colormatic options everything is turned off

Let me know if you need any more info! :)

**Comment by kvverti** [comment]
Cannot reproduce in 1.16.3. Is 1.16.4 required for this to occur (Colormatic works in both versions).

**Comment by kvverti** [comment]
Closed due to inactivity
