### ISSUE TITLE
[1.16.4] Night Vision at night makes everything black

### ISSUE THREAD

**Issue by ShabanPlayz** [kvverti/colormatic#25]
When using this mod without a resource pack (didn't try with a resource pack on) and applying night vision while it's night makes everything completely black. The blocks? Black. Mobs? Black. Items in inventory? Black. Text in options screen? Black. It looks exactly like [MC-165208](https://bugs.mojang.com/browse/MC-165208)

**Comment by ShabanPlayz** [comment]
[The same issue appears in clear skies](https://github.com/grondag/clear-skies/issues/4) so you guys could maybe solve the issue together

**Comment by kvverti** [comment]
Does this issue only occur when the Clear Skies option is enabled?

**Comment by ShabanPlayz** [comment]
this issue occurs when:
1. clear skies without colormatic is installed
2. colormatic without clear skies is installed
3. both are installed.
however since you can't reproduce it, it seems to be a compatibility issue with another mod so i'll have to investigate
