### ISSUE TITLE
Lightmaps don't work

### ISSUE THREAD

**Issue by Euclase777** [kvverti/colormatic#27]
Lightmaps don't work on minecraft 1.16.4

**Comment by Euclase777** [comment]
I wanted torches to emit blue light, so I made lightmaps with this idea. I put them in colormatic/lightmap and called world0.png but nothing changed in game. What am I doing wrong?

**Comment by kvverti** [comment]
Colormatic does not accept `world0` naming in the `colormatic` namespace, only in the `minecraft:optifine` path
