### ISSUE TITLE
[Colormatic v2.2.8] Mixin attempts to load Sodium mixins, causing spurious log warning

### ISSUE THREAD

**Issue by Abbanon** [kvverti/colormatic#28]
**Minecraft Version:** 
- 1.16.4

**The only mods enabled/active:**
- Colormatic v2.2.8
- Fabric API v0.29.3
- Mod Menu v1.14.13

**Full log:**
- https://paste.ee/p/IPZBC

**The error in question:**
- `[main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/world/WorldSlice (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/world/WorldSlice)`

**Notes/Misc:**
- I have verified that the issue is caused solely by Colormatic. 
- The error does not appear when adding **Sodium v0.1.0** to the list of active mods.
- Is this an issue? Or can it be disregarded?

**Comment by kvverti** [comment]
This error can be safely disregarded.

**Comment by kvverti** [comment]
The offending mixin is no longer present.
