### ISSUE TITLE
[Colormatic V2.2.8] Strange things happen when trying to render a litematica schematic with anything that "changes color"

### ISSUE THREAD

**Issue by GitSugar** [kvverti/colormatic#29]
Each time I load a Litematica schematic with colormatic enabled it immediately crashes the game. I can paste the latest crashlog I have but the TLDR thing is:

`java.lang.ClassCastException: fi.dy.masa.litematica.render.schematic.ChunkCacheSchematic cannot be cast to io.github.kvverti.colormatic.colormap.ColormaticBlockRenderView`

I already posted this issue in the litematica side, but just to be safe I'll leave it here too.
[crash-2021-03-05_14.07.58-client.txt](https://github.com/kvverti/colormatic/files/6096313/crash-2021-03-05_14.07.58-client.txt)

**Comment by kvverti** [comment]
This issue should be resolved in the next release, as Colormatic will transition to using the vanilla color resolver mechanism.

**Comment by kvverti** [comment]
Should be fixed in 2.2.9.
