### ISSUE TITLE
Resource loading screen in color.properties

### ISSUE THREAD

**Issue by iforgotpassment** [kvverti/colormatic#32]
Optifine has a way to change the resource loading screen colors in color.properties: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties#L275
I really like this property in my resource packs, but sadly colormatic doesn't have this (and so does mcpatcher's version). I think this is a great idea, but that's my opinion. Please give it a thought.

Example:
![Dark mode resource loading screen](https://user-images.githubusercontent.com/82340554/114320936-b568d980-9b18-11eb-93a3-4e2358f7a45a.png)

**Comment by kvverti** [comment]
Mojang's brand guidelines preclude using other color schemes on their loading screen.
