### ISSUE TITLE
Crash in minecraft 1.16.1

### ISSUE THREAD

**Issue by Fantasmatico7824** [kvverti/colormatic#33]
I use Fabric 1.16.1, but when using the mod, I just place it in the mods folder and start the game, it crashes with error 0, I already tried to reinstall the whole game, saving certain files such as launcher skins, mods, texture packs, etc. but it keeps crashing, I also tried updating the java, but it continues 
![Minecraft Launcher 14_04_2021 09_17_28 a  m](https://user-images.githubusercontent.com/70528642/114725676-4cdd5080-9d02-11eb-815b-2f1592e4c473.png)

 I have tried to see if there are any mods that cause a crash, but, just having Optifine and mods that help the game work, it is enough for it to crash (I'm from Mexico, that's why some addresses and files are in Spanish) 
![mods 14_04_2021 09_16_01 a  m](https://user-images.githubusercontent.com/70528642/114725401-143d7700-9d02-11eb-9a46-49a7f8ccecfc.png)

**Comment by kvverti** [comment]
Colormatic is not compatible with Optifine.
