### ISSUE TITLE
Incompatible with Sodium 0.2.0

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [kvverti/colormatic#36]
Sodium 0.2.0 breaks colormatic. It has not been released yet (this is the commit that broke it I believe: https://github.com/CaffeineMC/sodium-fabric/commit/f4d08208a91da6166f82a6deb40dc4af1007b2b9), but there are plans by CaffeineMC to release Sodium 0.2.0 (for 1.16.5) soon.

**Comment by kvverti** [comment]
There are currently no plans for continued development of Colormatic for 1.16.x. Current efforts are focused on a 1.17 release, after which all updates will be to the 1.17 version.

**Comment by kvverti** [comment]
That being said, the issue should be fixed in the 1.17 version, and it may be possible to backport a fix.
