### ISSUE TITLE
Incompatible with sodium (again)

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [kvverti/colormatic#40]
Using this mod with the 1.17 branch of sodium crashes on startup ([log](https://gist.github.com/DragonEggBedrockBreaking/8bc34c5a69b1aecc5ff533dd6f217433)).

I believe that this can be temporarily fixed by putting `mixin.features.fast_biome_colors=false` into `.minecraft/config/sodium-mixins.properties` and can be temporarily fixed on this mod's side by putting the following into `src/main/resources/fabric.mod.json`:

```json
"custom": {
    "sodium:options": {
        "mixin.features.fast_biome_colors=false": false
    }
},
```

**Comment by kvverti** [comment]
There are currently no plans to develop Colormatic against unstable, unreleased Sodium builds.

**Comment by DragonEggBedrockBreaking** [comment]
sodium 0.3.0 for 1.17 has now been released
