### ISSUE TITLE
Cannot change water particle color

### ISSUE THREAD

**Issue by royalhowl** [kvverti/colormatic#43]
I tried making own resource pack and cannot get custom water color to work. Portal particles work just fine. Should I be able to change color of the water particles?

My color.json
`{
 "particle": {
  "water": "ff9538",
  "lava": "ff9538",
  "portal": "ff9538"
  }
}`

Here's also latest log if that is any help.
[latest.log](https://github.com/kvverti/colormatic/files/6878866/latest.log)

![Screenshot 2021-07-26 170637](https://user-images.githubusercontent.com/44850068/127004144-8391c2c3-1312-432c-bd64-021f274c7262.png)
![Screenshot 2021-07-26 170819](https://user-images.githubusercontent.com/44850068/127004150-3780749e-b2af-4814-854c-a0d008e38d7b.png)

**Comment by kvverti** [comment]
Colormatic does not implement the base colors for water and lava particles because these particles are not colored.

**Comment by lumaGrade** [comment]
My bad, I just assumed they would work since they're present and it worked with optifine

**Comment by royalhowl** [comment]
My bad, I just assumed it should work since they're present and it worked with optifine.
