### ISSUE TITLE
Latest GHRelease doesn't boot

### ISSUE THREAD

**Issue by DestinyTheGreat** [kvverti/colormatic#47]
[latest.log](https://github.com/kvverti/colormatic/files/7027999/latest.log)

Ya not sure what else to say here, other people have tested this too and get identical errors

Edit: using version 2.2.10 from Github Releases

**Comment by kvverti** [comment]
Updated

**Comment by InboundBark** [comment]
[2021-08-24-7.log](https://github.com/kvverti/colormatic/files/7041225/2021-08-24-7.log)

**Comment by kvverti** [comment]
That log contains no errors

**Comment by InboundBark** [comment]
Sorry, I fixed the log now.
