### ISSUE TITLE
Game crashing at startup[bug]

### ISSUE THREAD

**Issue by Anoaxx** [kvverti/colormatic#49]
As simply as you can read. Having only colormatic 2.2.10 + cloth config 5.0.38 + fabric api 0.39.1 + mod menu 2.0.5 causes crash at startup without crashlogs. if i delete Colormatic everything is fine. I don't know why, because no one to this day don't write issue about this :/

**Comment by Rajbir98** [comment]
I also have these mods it doesn't happens with me
as all my mods are update to latest version

**Comment by Crystalis7** [comment]
Hi, I am also experiencing crashes when using Colormatic 2.2.10 with Modmenu 2.0.5 and Fabric API 0.37.2, 0.38.0,
0.39.0 or 0.40.0. I get the same crash using just Colormatic and Fabric API. I am using Windows 10 Pro and Java 16.0.1.9 (AdoptOpenJDK). Log is attached.

[crash-2021-09-06_00.09.48-client.txt](https://github.com/kvverti/colormatic/files/7112357/crash-2021-09-06_00.09.48-client.txt)

**Comment by Anoaxx** [comment]
> which operating system and java version plz
> log also

Oh. Win 10 and java 16

**Comment by Madis0** [comment]
Can confirm. It seems to only crash once though, before creating config perhaps?

MC 1.17.1, Colormatic 2.2.10, Fabric API 0.40.0, other mods as part of [Fabulously Optimized](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized) 2.1.0

[2021-09-06-1.log](https://github.com/kvverti/colormatic/files/7117331/2021-09-06-1.log)

**Comment by Vacony** [comment]
[crash-2021-09-06_14.04.25-client.txt](https://github.com/kvverti/colormatic/files/7117934/crash-2021-09-06_14.04.25-client.txt)

I'm having the same issue, here is a crash log that was provided.

OS: Windows 10 Home 19042.1165
Java version: Version 8 Update 301 (build 1.8.0_301-b09)
MC Version: 1.16.5

**Comment by Samisaprogrammer** [comment]
I can confirm this too
MC 1.17.1
Colormatic 2.2.10
Fabric api 0.40.1
modmenu 2.0.10
It consistently happens.

**Comment by kvverti** [comment]
Please install Cloth Config. It is no longer bundled with Colormatic due to its large size.

**Comment by Samisaprogrammer** [comment]
I have cloth config and it persists, reopen this.

**Comment by Madis0** [comment]
> Critical injection failure: Redirector proxySkyColor(Lnet/minecraft/class_243;Lnet/minecraft/util/CubicSampler$class_4859;Lnet/minecraft/class_243;F)Lnet/minecraft/class_243; in colormatic.mixins.json:world.ClientWorldMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap colormatic-refmap.json
 
That seems to be the cause... or one of the causes.

**Comment by Anoaxx** [comment]
I have  cloth config built in in other mod. It appears in mod list so I have it. After putting colormatic in mods still crashes without crashlogg
