### ISSUE TITLE
Game crashing on startup

### ISSUE THREAD

**Issue by BurgBoi** [kvverti/colormatic#50]
It's kind of self explanatory: the game is crashing on startup.
I don't know if it's just a compatibility thing or not so I will include what mods I'm using.

Error message:
`The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'colormatic'!
Exit Code: -1`

I'm using these mods:
![explorer_tJukSHZmIX](https://user-images.githubusercontent.com/53149876/131234805-248b0612-4d4b-4edf-bad5-1ee8340cbe1e.png)
Crash report:
[crash-2021-08-28_21.03.27-client.txt](https://github.com/kvverti/colormatic/files/7071732/crash-2021-08-28_21.03.27-client.txt)

Edit: It's definitely not a compatibility issue, removed all other mods except fabric api and modmenu and the game was still crashing.

**Comment by Anoaxx** [comment]
im not the one!

**Comment by Cardistymo** [comment]
same for me!

**Comment by Rajbir98** [comment]
its working for me it doesn't crash i my case

**Comment by Spectralitree** [comment]
the same is happening to me, same error message too!

**Comment by kvverti** [comment]
Colormatic no longer bundles Cloth Config. You must use ClothConfig alongside Colormatic in order for it to work.
