### ISSUE TITLE
Crash On Loading World (NullPointerException)

### ISSUE THREAD

**Issue by TheLegitStick** [kvverti/colormatic#54]
Here is my full crash report, including PC specs, mod list, etc...
https://bytebin.lucko.me/gqMNwZN6vM

As stated, the game only crashes upon loading into a world.

**Comment by kvverti** [comment]
Duplicate of #51

**Comment by kvverti** [comment]
Wait wrong issue

**Comment by kvverti** [comment]
Do any of the mods you have installed add overworld biomes?
