### ISSUE TITLE
Lava cannot be biome tinted

### ISSUE THREAD

**Issue by Justsnoopy30** [kvverti/colormatic#62]
A pack that can reproduce this is linked here: https://www.planetminecraft.com/texture-pack/incendium-s-optionnal-resourcepack-remix/
In overworld biomes and vanilla nether biomes, the lava should be orange, but instead it is purple-white, the greyscaled texture for the lava to be colormapped.

**Comment by bbharier** [comment]
Very excited for this next release <3
