### ISSUE TITLE
Loading Screen colors not working!

### ISSUE THREAD

**Issue by Erallie** [kvverti/colormatic#63]
Hello,

None of the options for the loading screen colors are working with colormatic, and neither does the custom loading screen icon show up. Nothing changes from the default mojang loading screen when I use colormatic with my resource pack. Can you please fix this?

**Comment by kvverti** [comment]
Colormatic intentionally does not implement custom loading screen colors. This is to preserve Mojang's logo and brand.

**Comment by kvverti** [comment]
Also duplicate of #32
