### ISSUE TITLE
Mod 'Colormatic' (colormatic) requires "version 0.37.1 or later" of fabric, which is missing!

### ISSUE THREAD

**Issue by scamdotnet** [kvverti/colormatic#66]
Hi, I'm having an issue with Colormatic 2.3.1 for 1.17.1 where when I attempt to launch the game, the mod states that it requires version 0.37.1 or later of fabric, which as far as I know doesn't exist.

Fabric Version: 0.12.5
Launcher: MultiMC
Mods: Carpet Mod 1.4.54, Cloth Config v5 5.1.40, Colormatic 2.3.1+mc.1.17.1, Litematica 0.0.0-dev.20210906.183617, MaLiLib 0.10.0-dev.26
Minecraft Log: https://paste.ee/p/SYdsL

**Comment by scamdotnet** [comment]
I found the cause of the issue. It isn't a version of fabric it is asking for, it is infact looking for fabric**API**. If there is any way to make this error message more specific, I and probably other users would be very happy.
Thanks,
              Scam.net

**Comment by kvverti** [comment]
The error message is displayed by Fabric Loader; I don't have control over what it looks like.

**Comment by scamdotnet** [comment]
Okay, thanks for replying
