### ISSUE TITLE
Quilt-loader question

### ISSUE THREAD

**Issue by Yurinann** [kvverti/colormatic#67]
I use Minecraft 1.18 Release with Fabric 0.12.8, and colormatic.
When I start my client, it failed start and say "colormatic need quilt-loader"

**Comment by Yurinann** [comment]
It may be my problem, to be further confirmed.

**Comment by Yurinann** [comment]
Some times the client will crash and show the above reason.

**Comment by kvverti** [comment]
The recommendation for "quilt-loader" is purely cosmetic.
