### ISSUE TITLE
Colormatic not working with Nox's Better Carpets

### ISSUE THREAD

**Issue by TravelerHD** [kvverti/colormatic#69]
Apologies in advance if this isn't a good place to mention this issue. Colormatic isn't working with Nox's Better Carpets on Minecraft 1.18. When applying the pack the carpets don't change. The resource pack was create for 1.17 so that could be the issue, but Optifine seems to load the pack fine so I'm not sure what to make of it. Is there something I can change in the resource pack's files, or is this a bug that needs to be fixed in Colormatic?

**Comment by kvverti** [comment]
Nox's Better Carpets uses CTM, not custom colors. Custom textures for carpets is already possible in vanilla via block models - I'm not sure why Nox feels it necessary to use Optifine's CTM for this.
