### ISSUE TITLE
Custom colormaps don't use new biome ids

### ISSUE THREAD

**Issue by JermsyBoy** [kvverti/colormatic#70]
I've noticed any colormaps in my pack that aren't grass or leaves (water, sky, birch, etc) aren't matching up with the new 1.18 biome ids, and instead are still using the 1.17 ids.

**Comment by kvverti** [comment]
This is intentional so that resource packs do not need to shuffle columns. Did Optifine just decide to go full breakage?

**Comment by JermsyBoy** [comment]
yeah optifine switched to the 1.18 ids so unfortunately packs won’t be compatible with both mods. IMO if you’re gonna keep optifine’s format i think you should update to the new ids, even if it means people will have to update their packs. Just my opinion though :)

**Comment by kvverti** [comment]
That's annoying. I kind of hoped Optifine would also use the 1.17 columns, but maybe I expected too much

**Comment by JermsyBoy** [comment]
To be fair, they did remove a ton of biomes from the game so it was kinda necessary to change it i feel

**Comment by Enchanted-Games** [comment]
Just wondering are you going to make the mod use the new 1.18 IDs? I would like to know if I should fix my packs or not

**Comment by kvverti** [comment]
The next update will use the raw IDs for vanilla biomes in the current version by default (same as Optifine), but you will be able to set `variant = legacy` (I think that’s what I called it) to use the old 1.17 IDs (including using the 1.17 equivalent datapack biome IDs in Optifine style packs), or `variant = stable` to use the 1.18 columns with the guarantee that they will never change in the future

**Comment by Enchanted-Games** [comment]
Nice, glad you found a way to use both options aswell
