### ISSUE TITLE
Biome coloring not working

### ISSUE THREAD

**Issue by ClayBCE** [kvverti/colormatic#72]
After installing Colormatic, everything appears to work; though in biomes with custom coloring for grass and leave blocks, it is automatically reverting to green regardless of the biome (instead of in my case it being purple in my Skylands biome).

**Comment by kvverti** [comment]
Please provide your resource pack.

**Comment by ClayBC** [comment]
I am currently using New Default+, Tissou's Zombie Pack, and Better botanicals and vegetation.

**Comment by kvverti** [comment]
Do you have a datapack as well?

**Comment by ClayBC** [comment]
I'm not 100% sure. I am using Better Minecraft for 1.18.1 modpack. Couldn't find a datapack folder in my install and the datapack folder on the server is empty.

**Comment by kvverti** [comment]
Do you have a Colormatic colormap defined for grass and leaves? Colormatic will apply custom colormaps to _all_ biomes, even custom biomes.
