### ISSUE TITLE
Crash whilst joining world with sodium 1.18.1-alpha6

### ISSUE THREAD

**Issue by PlanetSun3** [kvverti/colormatic#74]
Colormatic crashes with the new sodium release. The crash is due to the changes in the code revolving around color in commit https://github.com/CaffeineMC/sodium-fabric/commit/c1f71f72054f2d4826b3236c8bf8c9aa41459454. 

Logs: 
[latest.log](https://github.com/kvverti/colormatic/files/7867060/latest.log)

**Comment by keatit71** [comment]
Had the same issue colormatic doesn't work with the new sodium version.
[2022-01-14-7.log](https://github.com/kvverti/colormatic/files/7869380/2022-01-14-7.log)

**Comment by DragonEggBedrockBreaking** [comment]
Does putting `mixin.features.chunk_rendering=false` in sodium config fix it?

**Comment by MeeniMc** [comment]
I have been using the latest build and it works good. Any reason why you are holding the release? (just so I know if there are some major bugs to be afraid off).

**Comment by PlanetSun3** [comment]
Closing as 3.1.0 was released today. Thanks!
