### ISSUE TITLE
[Feature Request] Compatibility with Iris 1.2.0

### ISSUE THREAD

**Issue by Goldenfreddy0703** [kvverti/colormatic#76]
Hey there, 2 days ago The Iris team released Iris 1.2.0 and i was wondering if you could make this mod compatible with the latest version of Iris. 

Thank you

**Comment by BluSpring** [comment]
I believe they added Colormatic 3.0.0 to crash for Iris due to the Sodium issue. As far as I'm aware it is actually compatible with the PR I did (#75), you just need to edit Iris' fabric.mod.json file and remove the line referencing Colormatic from it.

**Comment by Goldenfreddy0703** [comment]
Oh ok, thank you very much, I will try that soon.
