### ISSUE TITLE
Broken with gammas above 1.0

### ISSUE THREAD

**Issue by Gaming32** [kvverti/colormatic#77]
Colormatic bugs out visually when the gamma is set above 1.0 (Bright in the settings GUI). This is a problem because many people play with a higher gamma. I play with 2.0 (200% in the settings GUI).

Cause of issue #52.

**Comment by kvverti** [comment]
Brightness above 100% is unsupported in vanilla Minecraft and can lead to glitches.

**Comment by Gaming32** [comment]
If you want me to not use Colormatic, okay! I'll go find a different mod.

**Comment by Gaming32** [comment]
I have identified and fixed the issue in [my fork](https://github.com/Gaming32/colormatic-fixed-gamma). Would you like to submit a PR?
