### ISSUE TITLE
Version 3.0.0 does not work with Iris 1.2.0

### ISSUE THREAD

**Issue by MineSweeper73** [kvverti/colormatic#78]
It's all in the title. Game fails to load with both colormatic 3.0.0 and iris-1.2.0. Iris 1.2.0 just does not work with the current version of colormatic.

**Comment by BluSpring** [comment]
If you build #75 from source, you should hopefully be able to add Colormatic to Iris.

**Comment by corhean** [comment]
excited to see a release of this, I have a friend who is very interested in changing the color of redstone lines :D
