### ISSUE TITLE
Manually compiled 3.0.1 version causes errors and breaks connection to 1.8 server with multiconnect

### ISSUE THREAD

**Issue by REALMWTH** [kvverti/colormatic#80]
So, I've built the latest version of Colormatic and installed multiconnect.
Tried to connect to minemen server using 1.8 minecraft protocol and has crash
Removing mod and/or connecting to 1.18.1 servers doesn't cause this issue
Log is below
[latest.log](https://github.com/kvverti/colormatic/files/7967688/latest.log)

**Comment by kvverti** [comment]
Colormatic does not support versions before 1.14.

**Comment by REALMWTH** [comment]
Client version is 1.18.1

**Comment by kvverti** [comment]
The 1.8 networking protocol is not compatible with 1.18.1. Colormatic relies on a networking protocol at least > 1.16.2.
