### ISSUE TITLE
Incorrect emulation of lightmaps.

### ISSUE THREAD

**Issue by coornio** [kvverti/colormatic#82]
Specifically I am using the John Smith Legacy resource pack. To my understanding it uses custom color values for certain light sources and such, so Colormatic was right up my alley to use. 

Back to the issue at hand. Here is what it looks like through Optifine itself:

![2022-02-13_18 00 31](https://user-images.githubusercontent.com/11655762/153761826-95a50e86-9f77-419e-9146-1ac5794d4903.png)

This is what it looks like in Fabric/Sodium/Starlight when Colormatic isn't loaded as a mod:

![2022-02-13_18 07 16](https://user-images.githubusercontent.com/11655762/153761844-813e06eb-0b04-45e0-8598-e0a27546c113.png)

And this is what happens when it _is_ loaded:

![2022-02-13_17 59 41](https://user-images.githubusercontent.com/11655762/153761859-aafb2a89-4cfe-4c5e-a4a3-3745d4bbde9b.png)

I'm fairly certain this isn't supposed to be this way. This bug might be affecting more than just this particular resource pack but I can't know for sure as I don't actually use any others.

Based on some blind searching, I figured out which assets in particular caused this disparity. They are located under `assets/minecraft/optifine/lightmap`, three different maps that dictate, to my understanding, the kind of light sources produce. For convenience, I will attach these files here directly for review. 
![world0](https://user-images.githubusercontent.com/11655762/153766036-e08f4cc0-b58c-460b-b60d-421b144091b9.png)
![world1](https://user-images.githubusercontent.com/11655762/153766040-ae62c3a8-1f52-46a8-9d9a-0747bd8074b5.png)
![world-1](https://user-images.githubusercontent.com/11655762/153766042-5434c898-81c0-4221-853b-7aa466a444e5.png)

Removing them manually from the resource pack, the light goes right back to normal. I have brought up this situation on the John Smith Legacy discord as well to get their thoughts on the matter.

Ideally I'd like to continue using the custom lightmaps. A potential side-effect of this wrong emulation is that game text turns yellowish/orangish during night hours, which at first I thought was a feature of the mod itself. On the one hand I love that aspect of it, but on the other hand I can't use it when all light sources produce incorrect lightmaps because of this mod.

Please review and let me know if there's something more I can provide or what could be done about this.

**Comment by kvverti** [comment]
What is your brightness setting?

**Comment by kvverti** [comment]
It seems that Optifine uses a different color blending algorithm than Colormatic. I don't know Optifine has changed recently or not.

**Comment by kvverti** [comment]
I think I've found the issue. Colormatic uses `max(block, sky)` to calculate the combined color instead of `block + sky`. I've fixed it for the next release but I'll need to do a bit more testing to make sure it looks all right.

**Comment by coornio** [comment]
> I think I've found the issue. Colormatic uses `max(block, sky)` to calculate the combined color instead of `block + sky`. I've fixed it for the next release but I'll need to do a bit more testing to make sure it looks all right.

That's great to hear! Here's hoping this will also include the Iris fix from #78 when it drops :)

**Comment by coornio** [comment]
In case it helps, I can also build the source on my own to do testing. I attempted to make some changes based on what you said in the last comment (presumably L#158 in `LightmapTextureManagerMixin.java` I think?) but nothing I did made a change so I clearly have no idea what I'm doing there :D 

If you make any commits, just let me know if there's any particular scenarios to test and I can get back to you here with the results!

**Comment by coornio** [comment]
I would like to point out that by the time [this commit](https://github.com/kvverti/colormatic/commit/4059ac9bcd70793775aa567f903ce6af56bb5411) took place, the lightmaps were proper once again. All is well in 3.1.0 too so we can consider the issue itself resolved! <3

I have to say though, I'll miss the bug of the font turning yellow at night time. It was much easier on the eyes in dark environments. Hope you might consider adding that sort of thing as an option in a future version!
