### ISSUE TITLE
Crash on game load 'Mixin apply'

### ISSUE THREAD

**Issue by nc-z** [kvverti/colormatic#85]
This seems to be causing a crash on my Mac. I can replicate this with only the Fabric API, Cloth-Config, Mod Menu, and Colormatic mods.

A log is here: https://paste.ee/p/Hwzns

**Comment by nc-z** [comment]
After seeing another issue about Sodium and mixin, I'll add that it also crashes when I have sodium-fabric-mc1.18.2-0.4.1+build.15.jar installed. I just stripped down my mods for the sake of a cleaner bug report.

**Comment by kvverti** [comment]
Colormatic does not currently have a release compatible with 1.18.2.
