### ISSUE TITLE
Incompatible with Mod Menu 4.0.0

### ISSUE THREAD

**Issue by TheParadoxBox** [kvverti/colormatic#98]
An excerpt from the crash log:

> `- Mod 'Colormatic' (colormatic) 3.1.2+mc.1.19 recommends any version between 3.0.0 (inclusive) and 4- (exclusive) of mod 'Mod Menu' (modmenu), but only the wrong version is present: 4.0.0!`

I don't know how Colormatic works internally, but my best guess is that compatibility might be restored with a simple dependency version bump.

**Comment by osfanbuff63** [comment]
Cannot confirm, runs fine for me.
